baseurl      = "https://ac-hicks.com"
title        = "Andrew (Colter) Hicks"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My Online Front Page"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Andrew Hicks Home Page"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Andrew (Colter) Hicks"
    subtitle = "My Online Front Page"
    keywords = ""
    copyright = '<a href="https://colterhicks.com" target="_blank" rel="noopener">A Colter Hicks Site</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Andrew (Colter) Hicks"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://colterhicks.com"