baseurl      = "https://ac-hicks.com"
title        = "Andrew (Colter) Hicks"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My Online Front Page"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true
  disableRSS            = true

  # Metadata mostly used in document's head
  description = "Andrew Hicks Home Page"
  keywords = "homepage, blog"
  images = [""]

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[author]
  name = "Andrew Hicks"

[languages]
  [languages.en]
    title = "Andrew (Colter) Hicks"
    subtitle = "My Online Front Page"
    keywords = ""
    copyright = 'Copyright <a href="https://colterhicks.com">A Colter Hicks Site</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Andrew (Colter) Hicks"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# Uncomment this if you want a portrait on your start page
  
  [params.portrait]
     path     = "/images/Colter-Profile.jpg"
  #   alt      = "Portrait"
  #   maxWidth = "60px"



# Social icons

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/ColterHicks"

[[params.social]]
    name = "github"
    url = "https://github.com/RubeHicksCube"

[[params.social]]
    name = "facebook"
    url  = "https://facebook.com/RubeHixCube"

[[params.social]]
    name = "email"
    url  = "mailto:site@ac-hicks.com"

#  twitter = "RubeHicksCube"
#  instagram = "rubehickscube"
#  url = "https://colterhicks.com"
#  resume = "/files/Andrew Hicks Resume Public.pdf"
#  lastmod = true
#  disqusShortname = "rubehickscube"

[[params.links]]
  title = "Link"
  href = "https://colterhicks.com"
  icon = "/images/HyperCubeIcon.png"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://colterhicks.com"

[params.footer]
    trademark = true
    # rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      ""
    ]
